site_name: gportal-python
site_description: Python CSW (Catalog Services for the Web) and SFTP client for JAXA G-Portal.
site_author: Takahiro Miyoshi

repo_url: https://github.com/sankichi92/gportal-python
repo_name: sankichi92/gportal-python

nav:
  - index.md
  - Examples:
      - examples/search.ipynb
      - examples/sftp.ipynb
  - api.md

theme:
  name: material
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=palette#system-preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.footer
    - toc.integrate
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.magiclink
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#configuration
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.superfences
