[tool.poetry]
name = "gportal"
version = "0.1.0"
description = "CSW (Catalog Services for the Web) and SFTP client for JAXA G-Portal"
authors = ["Takahiro Miyoshi <takahiro-miyoshi@sankichi.net>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/sankichi92/gportal-python"
packages = [{include = "gportal"}]

[tool.poetry.dependencies]
python = "^3.8.1"
requests = "^2.28.2"
paramiko = "^3.1.0"

[tool.poetry.group.dev.dependencies]
black = {extras = ["jupyter"], version = "^23.1.0"}
isort = "^5.12.0"
flake8 = "^6.0.0"
pytest = "^7.2.2"
responses = "^0.23.1"

[tool.poetry.group.notebook.dependencies]
notebook = "^6.5.3"
geopandas = "^0.12.2"
matplotlib = "^3.7.1"
folium = "^0.14.0"
mapclassify = "^2.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
